### ISSUE TITLE
注册显示500。不知道咋办

### ISSUE THREAD

**Issue by hxer520** [YunYouJun/kotodama#10]
<img width="373" alt="image" src="https://user-images.githubusercontent.com/12802662/187927962-8f3e40d0-7030-4447-bad7-844f8c2f937e.png">

**Comment by YunYouJun** [comment]
注册须使用你自己的 Waline 后端，且确保已开放安全域名。

https://waline.js.org/reference/server.html#securedomains

<img width="784" alt="image" src="https://user-images.githubusercontent.com/25154432/188480236-f341db0f-3a2a-4050-9fad-d13307d0a062.png">
