### ISSUE TITLE
[bug report]刷新界面后无法加载，提示请求失败，状态码500

### ISSUE THREAD

**Issue by krau** [YunYouJun/kotodama#12]
如图，登录成功后再刷新一次网页，会出现异常
![图片](https://user-images.githubusercontent.com/71133316/193464225-ca4061a8-feaa-47f9-ba50-99e449eb2d55.png)

![图片](https://user-images.githubusercontent.com/71133316/193464305-9c84fa4f-bfcc-4de5-9a50-311fb48bce03.png)

浏览器：Firefox

**Comment by YunYouJun** [comment]
无法复现，检查是否已开放安全域名。

**Comment by krau** [comment]
> 无法复现，检查是否已开放安全域名。

我的waline服务端部署于vercel，已经配置环境变量`SECURE_DOMAINS`来开放安全域名，依然存在此问题。
![图片](https://user-images.githubusercontent.com/71133316/193482980-760e422d-7037-40e9-ac67-bf3be9a0d3e0.png)

第一次登录成功后各种功能正常，但若使用浏览器的刷新，或是重新打开kotodama网页就会出现此问题。

**Comment by YunYouJun** [comment]
能否提供可测试使用的账号？

**Comment by krau** [comment]
> 能否提供可测试使用的账号？

好的，我将提供我的github与waline账号，请问如何发送给你？

**Comment by YunYouJun** [comment]
我的邮箱：me@yunyoujun.cn

**Comment by YunYouJun** [comment]
感谢反馈，排查应该是 authorization 的 headers 相关没有更新和重置，现已修复，可测试新版本是否可成功使用（我自己测试成功了）。

**Comment by YunYouJun** [comment]
还没部署，稍等一下。

**Comment by YunYouJun** [comment]
Vercel 我这边好像挂了……部署成功，但是访问无连接。

可以测试备用域名：https://kotodama.elpsy.cn/
没问题的话就关 Issue 吧。

**Comment by YiHui-Liu** [comment]
![1664941068267](https://user-images.githubusercontent.com/30190271/193976351-9177cae8-5372-4762-92a4-b0c118249043.png)

使用备用域名测试，仍然未修复，问题应该是默认请求到你自己的域名那边去了

**Comment by YiHui-Liu** [comment]
![1664941068267](https://user-images.githubusercontent.com/30190271/193976351-9177cae8-5372-4762-92a4-b0c118249043.png)

使用备用域名测试，仍然未修复，问题是默认请求到你自己的域名那边去了
图中有两个请求，分别是：
* https://waline.yunyoujun.cn/comment?type=list&owner=all&status=approved&keyword=&page=1
* https://waline.foolishfox.cn/comment?path=%2F&pageSize=10&page=1&lang=zh-CN&sortBy=insertedAt_desc
应该是代码有一个地方忘记代替默认值了

**Comment by YunYouJun** [comment]
已修复，再试试呢？你的网址似乎无法访问了。

![image](https://user-images.githubusercontent.com/25154432/194067272-4b60dea5-470b-4e8a-bf28-b4f1befb19ff.png)

**Comment by krau** [comment]
我这边测试还是有问题，依然是https://github.com/YunYouJun/kotodama/issues/12#issuecomment-1267892169 所述情况，刷新后有一个请求是到waline.yunyoujun.cn了
![图片](https://user-images.githubusercontent.com/71133316/194075680-ffa09980-1c58-4067-ae84-efb684b35e1a.png)

**Comment by YunYouJun** [comment]
是缓存的命名空间问题，这次应该真的修复了（

以及 `vercel.app` 国内似乎已经被污染了。

**Comment by krau** [comment]
> 是缓存的命名空间问题，这次应该真的修复了（
> 
> 以及 `vercel.app` 国内似乎已经被污染了。

我这边也没问题了，这次大概真的修复力（

那就关issue了

**Comment by YiHui-Liu** [comment]
> 是缓存的命名空间问题，这次应该真的修复了（
> 
> 以及 `vercel.app` 国内似乎已经被污染了。

https://kotodama.yunyoujun.cn/ 还是不可以

**Comment by krau** [comment]
> > 是缓存的命名空间问题，这次应该真的修复了（
> > 以及 `vercel.app` 国内似乎已经被污染了。
> 
> https://kotodama.yunyoujun.cn/ 还是不可以

我这边是三个域名都可以了，你退出并重新登录试下

**Comment by YiHui-Liu** [comment]
> > > 是缓存的命名空间问题，这次应该真的修复了（
> > > 以及 `vercel.app` 国内似乎已经被污染了。
> > 
> > 
> > https://kotodama.yunyoujun.cn/ 还是不可以
> 
> 我这边是三个域名都可以了，你退出并重新登录试下

🆗清理缓存后可以了
