### ISSUE TITLE
关于在waline应用reCAPTCHA的问题

### ISSUE THREAD

**Issue by imjason** [YunYouJun/kotodama#13]
waline在https://github.com/walinejs/waline/pull/1386 更新了reCAPTCHA V3
当应用了reCAPTCHA V3时Kotodama登陆会产生问题
希望适配一下

**Comment by YunYouJun** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/25154432/209400692-20ff426e-432e-4b1e-acb8-d7ec71719273.png">

适配完成，如需使用 [reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3)，需配置 reCAPTCHA V3 Key（此后将会被缓存）。
