### ISSUE TITLE
[Bug] 评论 API 似乎有变，没有返回 `createdAt` 字段。

### ISSUE THREAD

**Issue by zhuozhiyongde** [YunYouJun/kotodama#16]
### Describe the bug

我使用的是 Docker 部署的 waline，不太清楚 vercel 部署的？或许可以排查一下到底是 waline 的 API 与预期不一致，Docker 版本的没有正常返回字段，还是 Kotodama 没跟上 API 变动。

![image](https://github.com/user-attachments/assets/80de28bc-d884-4d2e-9630-4832a53c46b8)

Kotodama 的相关代码地址在 src/components/dashboard/CommentControl.vue 的 137 行，现在用的是 `createdAt` 但是实际 API 没有返回，这导致现在在 Kotodama 里面看都是当前时间戳。可以改成 `insertedAt`

```vue
      <div
        m="r-2"
        class="inline-flex items-center justify-start opacity-90"
        :title="t('dashboard.createdAt')"
      >
        <div i-ri-pencil-line class="mr-1" />
        <span>{{ dayjs(item.createdAt).format('YYYY-MM-DD HH:mm:ss') }}</span>
      </div>
```

### Reproduction

None

### System Info

```Shell
None
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
应该是 API 变化了。

但是之前是有根据 `createdAt` 与 `updatedAt` 是否一致，来决定是否显示`更新于`字段。

现在反而没有了……

**Comment by YunYouJun** [comment]
更新了。

**Comment by YunYouJun** [comment]
766fbb277401232fcb4909fa85b7694b0b3d9891

**Comment by zhuozhiyongde** [comment]
好快的修，为大佬点赞
