### ISSUE TITLE
[Feature Request] 登录信息持久化

### ISSUE THREAD

**Issue by zhuozhiyongde** [YunYouJun/kotodama#17]
### Clear and concise description of the problem

如题，现在感觉三天两头掉登录，每次都得重新登，但是不知道这个是 Waline 本身的设计还是 Kotodama 为了支持多站点特殊设计的？

### Suggested solution

设法持久化登录

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
登录态不是前端记录的，不过新添加了本地缓存登录 URL/用户名/密码，可以减少重新登录的麻烦。
