### ISSUE TITLE
[Feature Request]适配 `/ui` 子路径

### ISSUE THREAD

**Issue by lizheming** [YunYouJun/kotodama#3]
Waline server 端后台页面的路径会增加 `/ui` 前缀，所以希望能适配增加 `/ui` 前缀访问，另外针对这种场景可以直接使用 `location.protocol + '//' + location.hostname` 作为 serverURL。

同时针对 `/ui` 的场景可以隐藏到目前的首页，直接未登录跳转到登录页，已登录的跳转到列表页（非管理员则直接跳转到用户信息页）。

**Comment by YunYouJun** [comment]
不知重定向是指需要什么方案呢？

直接页面上的重定向是否可行？

https://github.com/YunYouJun/kotodama/blob/main/src/pages/ui.vue

**Comment by lizheming** [comment]
目前的设定是 serverURL 下的 path 除了 `/ui` 都是 API 的地址，所以页面的地址应该都是带 `/ui` 前缀的，例如 `/ui/login` `/ui/dashboard` 之类的

**Comment by YunYouJun** [comment]
页面部署于 `/ui` 的子路径，可通过配置 vite.config.ts 中的 `base` 来快速实现。之后我可以在文档中注明具体如何配置。

> https://vitejs.dev/config/#base

以及设想的是，既然已经是前后端分离的方式，那么 UI 这个层级完全可以脱离 server 的部署流程。
譬如 `api.waline.xxx.com` 为后端 serverURL域名，`kotodama.xxx.com` 为前端 UI 界面，两者流程上互不干扰。
如果用户不想自行部署，甚至还可以直接使用中心化的（通过纯静态站点以保证数据的隐私与安全） `kotodama.xxx.com` 来管理评论。

**Comment by lizheming** [comment]
申请两个域名对使用者来说比较麻烦，所以现在是使用的子路径区分，且这样也没有跨域的问题。那之后我 Fork 出来针对这块做一下修改吧~

**Comment by YunYouJun** [comment]
子域名对于有域名的用户来说成本不会增加，而使用第三方托管则有自动分配的域名，所以我觉得这个不是一个成本。跨域问题，我看到 Waline 里是有安全域名设置的。

**Comment by lizheming** [comment]
成本在于理解上面，不是所有的用户能分清楚前后端分离之类的概念的。服务端没有做跨域处理，安全域名是为了规避 CSRF 的
