### ISSUE TITLE
Microsoft Edge图标的更改

### ISSUE THREAD

**Issue by Lfhsheng** [YunYouJun/kotodama#7]
在评论后台，使用Edge的人评论时，显示的图标是旧版的，可以更改为新版。
[下载 Microsoft Edge Web 浏览器 | Microsoft](https://www.microsoft.com/zh-cn/edge?icid=SSM_AS_Promo_Other_Edge&r=1) 
~~🤡强迫症~~
同时，使用旧版Edge的就可以切换为旧版的图标😶

**Comment by YunYouJun** [comment]
不明白，希望可以截图说明。

**Comment by Lfhsheng** [comment]
![Microsoft Edge图标的说明](https://user-images.githubusercontent.com/74490140/146645425-71702e24-8cf4-4ac8-8e23-a5c30006cec1.png)

把上方第二个旧版Edge图标换成新版的 ~~严重强迫症~~

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/147470033-c3f028b8-cb0a-4bab-bb04-fb9b656a3783.png)

remixicon 很久没有更新了，没有新的 edge 图标。用了别的图标集，虽然有点风格稍微不一致，但是这样满意了吧（）

**Comment by Lfhsheng** [comment]
~~强迫症无语~~😏
