### ISSUE TITLE
完善下头像的显示

### ISSUE THREAD

**Issue by imjason** [YunYouJun/kotodama#8]
如题，把用户头像显示，不要用默认头像了吧

**Comment by YunYouJun** [comment]
用户头像就是显示的啊，前提是有配置过 Gravatar。
譬如该用户：

<img width="177" alt="image" src="https://user-images.githubusercontent.com/25154432/159040862-76e77f6c-018f-497f-812e-b2e738e8073d.png">

**Comment by imjason** [comment]
我这里似乎没有生效，配置过头像的也没有显示

**Comment by YunYouJun** [comment]
邮箱示例？

**Comment by imjason** [comment]
我QQ私聊你了

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/kotodama/commit/7ace4a2c42ae161d867fc8427e840b277146bdf8.
