### ISSUE TITLE
vercel显示将您重定向的次数过多

### ISSUE THREAD

**Issue by wlky-0106** [YunYouJun/kotodama#9]
自部署及kotodama.vercel.app显示将您重定向的次数过多,经过检查的网络录制后发现index.html重定向到本身,循环次数过多直接报错

**Comment by YunYouJun** [comment]
重定向过去主要为了解决 SSG 在 Vercel 下的问题，此前未发生该问题，也许 Vercel 对策略进行了一些变更。

GitHub Pages 版本正常：https://kotodama.yunyoujun.cn/

将会尽快修复。

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/kotodama/commit/8b81ddec4698f662fce9393f3768483a1469a828.
